from tkinter import *

parent = Tk()

firstname = Label(parent, text="First Name").grid(row=0, column=0)
e1 = Entry(parent).grid(row=0, column=1)
middletname = Label(parent, text="Middle Name").grid(row=1, column=0)
e2 = Entry(parent).grid(row=1, column=1)
lastname = Label(parent, text="Last Name").grid(row=2, column=0)
e3 = Entry(parent).grid(row=2, column=1)
address1 = Label(parent, text="Address 1").grid(row=3, column=0)
e4 = Entry(parent).grid(row=3, column=1)
address2 = Label(parent, text="Address 2").grid(row=4, column=0)
e5 = Entry(parent).grid(row=4, column=1)
postalcode = Label(parent, text="Postal Code").grid(row=5, column=0)
e6 = Entry(parent).grid(row=5, column=1)
city = Label(parent, text="City").grid(row=6, column=0)
e7 = Entry(parent).grid(row=6, column=1)
stateprovince = Label(parent, text="State/Province").grid(row=7, column=0)
e8 = Entry(parent).grid(row=7, column=1)
country = Label(parent, text="Country").grid(row=8, column=0)
e9 = Entry(parent).grid(row=8, column=1)
clear = Button(parent, text="Clear").grid(row=9, column=0)
submit = Button(parent, text="Submit").grid(row=10, column=0)

# window.title("Hello world")
# window.geometry("300x300")

# hello = tk.Label(text="Hello world!")
# hello.pack()
# button = tk.Button(text="Click me!")
# button.pack()
# tk.mainloop()
parent.mainloop()
